/* Generated By:JavaCC: Do not edit this line. XMLConstants.java */
package contacts.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPENADDRESSBOOK = 5;
  /** RegularExpression Id. */
  int CLOSEADDRESSBOOK = 6;
  /** RegularExpression Id. */
  int CLOSEGROUP = 7;
  /** RegularExpression Id. */
  int OPENCONTACT = 8;
  /** RegularExpression Id. */
  int CLOSECONTACT = 9;
  /** RegularExpression Id. */
  int OPENNAME = 10;
  /** RegularExpression Id. */
  int CLOSENAME = 11;
  /** RegularExpression Id. */
  int OPENNUMBER = 12;
  /** RegularExpression Id. */
  int CLOSENUMBER = 13;
  /** RegularExpression Id. */
  int OPENOWNID = 14;
  /** RegularExpression Id. */
  int CLOSEOWNID = 15;
  /** RegularExpression Id. */
  int OPENFRIENDS = 16;
  /** RegularExpression Id. */
  int CLOSEFRIENDS = 17;
  /** RegularExpression Id. */
  int OPENID = 18;
  /** RegularExpression Id. */
  int CLOSEID = 19;
  /** RegularExpression Id. */
  int OPENGROUP = 23;
  /** RegularExpression Id. */
  int TEXT = 24;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_OPENGROUP3 = 1;
  /** Lexical state. */
  int IN_OPENGROUP = 2;
  /** Lexical state. */
  int IN_OPENGROUP2 = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"<addressBook>\"",
    "\"</addressBook>\"",
    "\"</group>\"",
    "\"<contact>\"",
    "\"</contact>\"",
    "\"<name>\"",
    "\"</name>\"",
    "\"<number>\"",
    "\"</number>\"",
    "\"<ownid>\"",
    "\"</ownid>\"",
    "\"<friends>\"",
    "\"</friends>\"",
    "\"<id>\"",
    "\"</id>\"",
    "\"<group name=\\\"\"",
    "<token of kind 21>",
    "\"\\\"\"",
    "\">\"",
    "<TEXT>",
  };

}
